apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: icp4pkszs-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9f74e38aa6220ae0195286338184a7e7f1a498a5@sha256:deca6fc2df69202a1d3cc52b282d377d1377e7ca6a0005b2dfb8b07fcb14f830
          name: container-image
