apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: icp4pkszs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: icp4pkszs-go 
  name: icp4pkszs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: icp4pkszs-go 
